version: '3.9'

services:
  mariadb-tech-challenge :
    image: mariadb:${MDB_VERSION}
    container_name: mariadb-tech-challenge
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MDB_ROOT_PASS}
    volumes:
      - "./mariadb-data/data:/var/lib/mysql/data/"
      - "./mariadb-data/logs:/var/lib/mysql/logs/"
      - "./sql:/docker-entrypoint-initdb.d/:ro"
    ports:
      - 3306:3306
      
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8092:80
    environment:
      - PMA_ARBITRARY=1 

networks:
  app_network:
    driver: bridge