version: '3'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://192.168.15.122:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - zookeeper
      - kafka
    ports:
      - 8090:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

  kafka-init-topics:
    image: confluentinc/cp-kafka:latest
    volumes:
       - ./data/message.json:/data/message.json
    depends_on:
      - kafka
    command: "bash -c 'echo Waiting for Kafka to be ready... && \
               cub kafka-ready -b kafka:9092 1 90 && \
               kafka-topics --create --topic pagamento.solicitado --partitions 2 --replication-factor 1 --if-not-exists --bootstrap-server kafka:9092 && \
               kafka-topics --create --topic pagamento.pendente --partitions 2 --replication-factor 1 --if-not-exists --bootstrap-server kafka:9092 && \
               kafka-topics --create --topic pagamento.aceito --partitions 2 --replication-factor 1 --if-not-exists --bootstrap-server kafka:9092 && \
               kafka-topics --create --topic pagamento.recusado --partitions 2 --replication-factor 1 --if-not-exists --bootstrap-server kafka:9092 && \
               kafka-topics --create --topic pagamento.finalizado --partitions 2 --replication-factor 1 --if-not-exists --bootstrap-server kafka:9092 && \
               kafka-topics --create --topic pedido.status --partitions 2 --replication-factor 1 --if-not-exists --bootstrap-server kafka:9092 && \
               kafka-topics --create --topic pagamento.solicitado.DL --partitions 2 --replication-factor 1 --if-not-exists --bootstrap-server kafka:9092 && \
               kafka-topics --create --topic pagamento.pendente.DL --partitions 2 --replication-factor 1 --if-not-exists --bootstrap-server kafka:9092 && \
               kafka-topics --create --topic pagamento.aceito.DL --partitions 2 --replication-factor 1 --if-not-exists --bootstrap-server kafka:9092 && \
               kafka-topics --create --topic pagamento.recusado.DL --partitions 2 --replication-factor 1 --if-not-exists --bootstrap-server kafka:9092 && \
               kafka-topics --create --topic pagamento.finalizado.DL --partitions 2 --replication-factor 1 --if-not-exists --bootstrap-server kafka:9092 && \
               kafka-topics --create --topic pedido.status.DL --partitions 2 --replication-factor 1 --if-not-exists --bootstrap-server kafka:9092'"