version: '3.9'

services:
  redis:
    image: redis:7-alpine
    container_name: redis-tech-challenge    
    ports:
      - "6379:6379"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge